#!/usr/bin/env python3
from lib.faceswap import Faceswap
from glob import glob
from os.path import splitext, basename
import sys
import argparse
import logging

logger = logging.getLogger(__name__)

parser = argparse.ArgumentParser(description = "Displays the features of face on head")
parser.add_argument('head', type = str, nargs='?')
parser.add_argument('face', type = str, nargs='?')
parser.add_argument('-pp', '--predictor-path', type = str, default = "./landmarks.dat")
parser.add_argument('-o', '--output', type = str, default = "out.jpg")
parser.add_argument('-id', '--indirectory', type = str)
parser.add_argument('-od', '--outdirectory', type = str)
parser.add_argument('-v', '--verbose', action="store_true")
args = parser.parse_args()

if args.verbose:
    logging.basicConfig(level=logging.DEBUG)

swapper = Faceswap(predictor_path = args.predictor_path, verbose = args.verbose)

if args.indirectory and args.head and args.outdirectory:
    for path in glob("%s/*" % args.indirectory):
        base = splitext(basename(path))[0]
        out = "%s/%s.jpg" % (args.outdirectory, base)
        logger.debug("Processing %s -> %s" % (path, out))

        try:
            swapper.faceswap(head = args.head, face = path, output = out)
        except:
            logger.error("Couldn't convert this face")
elif args.head and args.face:
    swapper.faceswap(head = args.head, face = args.face, output = args.output)
else:
    parser.print_help()