#!/bin/bash
mkdir video-a
mkdir video-b
mkdir video-out
./videotool extractframes $1 -o video-a -v
./videotool extractframes $2 -o video-b -v
./faceswap video-a video-b video-out -v
cd video-out
rename -N 0001 's/.*/$N.jpg/' *
cd ..
./videotool combineframes video-out -o $3 -v
rm -r video-a
rm -r video-b
rm -r video-out