#!/usr/bin/env python3
from lib.videotool import Videotool
from glob import glob
from os.path import splitext, basename
import sys
import argparse
import logging

logger = logging.getLogger(__name__)

parser = argparse.ArgumentParser(description = "Handy video utilities")
parser.add_argument(
    'action',
    choices = ("extractframes", "combineframes"),
    required = True
)
parser.add_argument('-i', '--input', type = str)
parser.add_argument('-o', '--output', type = str)
parser.add_argument('-v', '--verbose', action="store_true")
args = parser.parse_args()

if args.verbose:
    logging.basicConfig(level=logging.DEBUG)

tool = Videotool(inp = args.input, out = args.output)

if args.action == "extractframes":
    tool.extractframes()
elif args.action == "combineframes":
    tool.combineframes()
else:
    parser.print_help()