#!/bin/bash
mkdir video-a
mkdir video-b
mkdir video-out
./videotool extractframes $1 -o video-a
./videotool extractframes $2 -o video-b
./faceswap video-a video-b video-out -v
./videotool combineframes video-out -o $3
rm -r video-a
rm -r video-b
rm -r video-out