BLUR_AMOUNT = 0.6
DATA_DIRECTORY = "./data"
DEFAULT_FRAMERATE = 30
DEFAULT_IMAGE_WIDTH = 600
DEFAULT_IMAGE_HEIGHT = 600
FEATHER_AMOUNT = 11
IMAGE_EXTENSIONS = (".jpg", ".png")
PREDICTOR_PATH = f"{DATA_DIRECTORY}/landmarks.dat"